name: lukas_generator
description: Lukas Generator Package help you to generate objects based on a template and custom params
version: '1.0.1'
homepage: https://github.com/rgprogra/lukas_generator
repository: https://github.com/rgprogra/lukas_generatorst

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
